name: AMG Dashboard Build & Test

on:
  push:
    branches:
      - $default-branch
      - dev
  pull_request:
    branches:
      - $default-branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_SEMVER: 3.11

    steps:
    - uses: actions/checkout@v3
    - name: "Setting up python${{ env.PYTHON_SEMVER }}"
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_SEMVER }}
        cache: 'pipenv'
    - name: Install pipenv
      run: pip install pipenv

    - name: Download stock sample data
      run: |
        mkdir -p data 
        wget https://raw.githubusercontent.com/plotly/datasets/master/stockdata2.csv -P data

    - name: Run pytests
      # Unable to use proper pytest invocation due to invalid test file names
      # pytest only recognized test_*.py or *_test.py automatically
      # run: |
        # pipenv install --dev
        # pipenv run pytest --junit-xml=test-results.xml 
      run: |
        pipenv install --dev
        pipenv run python -m pytest tests/test.py --junit-xml=test-results.xml

    - name: Failed test results
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: test-results.xml
